@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "classes.Ensayo",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1129098787 { 
   	label=systemAvg
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   SystemAvg388809307[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SystemAvg</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- getAverageByAge(newList: List&lt;Paciente&gt;, total: int): List&lt;Double&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAvgByAgeAndClinico(list: List&lt;Paciente&gt;): List&lt;Double&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAvgByAgeAndPcr(list: List&lt;Paciente&gt;): List&lt;Double&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAvgByWeeks(list: List&lt;Paciente&gt;): List&lt;Double&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_853620774 { 
   	label=classes
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Control853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Control&lt;T&gt;</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   fecha: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   resultado: T [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ passedAWeek(otherDate: LocalDate): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ControlClinico853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ControlClinico</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ControlLaboratorio853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ControlLaboratorio</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ControlPcr853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ControlPcr</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Ensayo853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Ensayo</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   estudio: Estudio [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   voluntarios: Set&lt;Voluntario&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ iniciarEstudio()</TD></TR>
<TR><TD ALIGN="LEFT" >+ registrarVoluntario(nombre: String, dni: String, sexo: String, edad: int, id: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ registrarVoluntario(v: Voluntario)</TD></TR>
<TR><TD ALIGN="LEFT" >+ reportarSintomas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ reportarSuspendidos()</TD></TR>
<TR><TD ALIGN="LEFT" >+ reporteGrupoVacuna()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Estudio853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Estudio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fechaInicio: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fechaInoculacion: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   placebo: List&lt;Paciente&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   suspendidos: List&lt;Paciente&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   vacuna: List&lt;Paciente&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- generarGrupoPlaceboYVacuna(set: Set&lt;Voluntario&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ informarResultadoControl()</TD></TR>
<TR><TD ALIGN="LEFT" >+ realizarControlGrupoPlacebo(p: Paciente, control: Control)</TD></TR>
<TR><TD ALIGN="LEFT" >+ realizarControlGrupoVacuna(p: Paciente, control: Control)</TD></TR>
<TR><TD ALIGN="LEFT" >+ registrarInoculacion()</TD></TR>
<TR><TD ALIGN="LEFT" >- suspenderConSintomas(list: List&lt;Paciente&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Paciente853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Paciente</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   controles: List&lt;Control&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addByTimeOfControl(c: Control): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ agregarControl(control: Control)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getControlsLabByTime(onlyFirstWeeks: boolean): List&lt;Control&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- needBeTested(c: Control): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ noTieneControlesPositivos(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ poseeClinicoPositivo(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ poseeControlLaboratorio(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ poseePcrPositivo(): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Voluntario853620774[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Voluntario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dni: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   edad: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sexo: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getByAge(minus: int, plus: int): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Control853620774 -> ControlClinico853620774[arrowhead=none, arrowtail=empty, dir=both];
Control853620774 -> ControlLaboratorio853620774[arrowhead=none, arrowtail=empty, dir=both];
Control853620774 -> ControlPcr853620774[arrowhead=none, arrowtail=empty, dir=both];
Ensayo853620774 -> Estudio853620774[label="estudio
[0..1]"];
Ensayo853620774 -> Voluntario853620774[label="voluntarios
[0..*]"];
Estudio853620774 -> Paciente853620774[label="placebo
[0..*]"];
Estudio853620774 -> Paciente853620774[label="suspendidos
[0..*]"];
Estudio853620774 -> Paciente853620774[label="vacuna
[0..*]"];
Paciente853620774 -> Control853620774[label="controles
[0..*]"];
Voluntario853620774 -> Paciente853620774[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml